count: 1  # 処理を繰り返す回数
is_upscale: false # 画像を拡大するか。アップスケールする場合はtrue
prompt: "dog riding a skateboard"
negative_prompt: "cat"
params:
  sampler_name: DPM++ 2M Karras
  steps: 8
  width: 512
  height: 512
  cfg_scale: 7
  seed: -1
  save_images: true
txt2img_params:
  alwayson_scripts:
    "Dynamic Prompts v2.11.1":
      args:
        - True  # is_enabled
        - False  # is_combinatorial
        - 0  # combinatorial_batches
        - False  # is_magic_prompt
        - False  # is_feeling_lucky
        - False  # is_attention_grabber
        - 0  # min_attention
        - 0  # max_attention
        - 0  # magic_prompt_length
        - ""  # magic_temp_value
        - 0  # use_fixed_seed
        - ""  # unlink_seed_from_prompt
        - ""  # disable_negative_prompt
        - null  # enable_jinja_templates
        - null  # no_image_generation
        - 0  # max_generations
        - ""  # magic_model
        - null  # magic_blocklist_regex
img2img_params:
  denoising_strength: 0.35
  script_name: "Ultimate SD upscale"
  script_args:
        - 0  # _
        - 512  # tile_width
        - 0  # tile_height
        - 24  # mask_blur
        - 64  # padding
        - 64  # seams_fix_width
        - 0.35  # seams_fix_denoise
        - 64  # seams_fix_padding
        - 3  # upscaler_index
        - True  # save_upscaled_image
        - 1  # redraw_mode
        - False  # save_seams_fix_image
        - 16  # seams_fix_mask_blur
        - 0  # seams_fix_type
        - 2  # target_size_type
        - 0  # custom_width
        - 0  # custom_height
        - 2.5  # custom_scale