f_prompt: # 最初に開始するプロンプト。ダイナミックプロンプトが有効なので、一回目はこのプロンプトを使用する。２回目以降からはパースされたプロンプトを使用する
  - |
    dog riding a skateboard.
    test
  - |
    bear in space suit
    test
f_negative_prompt: | # 最初に開始するネガティブプロンプト
  cat
  test
is_random_swap_width_height: false # 縦横サイズをランダムに入れ替えたい場合はtrueにする
size:
  - width: &w_1 512
    height: &h_1 512
  - width: &w_2 640
    height: &h_2 640
    scale: &scale_1 1.25
  - scale: &scale_2 1.5
default_params: &params
  sampler_name: DPM++ 2M SDE Karras
  steps: 8
  width: *w_1
  height: *h_1
  cfg_scale: 7
  seed: -1
  save_images: true
loopbacks:
  - api_endpoint: "/sdapi/v1/txt2img"
    params:
      <<: *params
      alwayson_scripts:
        "Dynamic Prompts v2.16.3":  &dp
          args:
            - True  # is_enabled
            - False  # is_combinatorial
            - 0  # combinatorial_batches
            - False  # is_magic_prompt
            - False  # is_feeling_lucky
            - False  # is_attention_grabber
            - 0  # min_attention
            - 0  # max_attention
            - 0  # magic_prompt_length
            - ""  # magic_temp_value
            - 0  # use_fixed_seed
            - ""  # unlink_seed_from_prompt
            - ""  # disable_negative_prompt
            - null  # enable_jinja_templates
            - null  # no_image_generation
            - 0  # max_generations
            - ""  # magic_model
            - null  # magic_blocklist_regex
  - api_endpoint: "/sdapi/v1/txt2img"
    params:
      <<: *params
      seed: -1
      width: *w_2
      height: *h_2
      enable_hr: false
      hr_scale: *scale_1
      hr_upscaler: "Latent" # "R-ESRGAN 4x+"
      denoising_strength: 0.7
      alwayson_scripts:
        "ControlNet":
          args:
            - input_image: null
              module: "tile_resample"
              model: "control_v11f1e_sd15_tile [a371b31b]"
              processor_res: 64
              threshold_a: 1
              threshold_b: 64
              resize_mode: 1  # Just Resize, Scale to Fit (Inner Fit), Envelope (Outer Fit)
        "Tiled VAE":
          args:
            - 0  # p
            - true  # enabled
            - 512  # encoder_tile_size
            - 64  # decoder_tile_size
            - true  # vae_to_gpu
            - true  # fast_decoder
            - true  # fast_encoder
            - false  # color_fix
  - api_endpoint: "/sdapi/v1/img2img"
    is_enabled: true # この値が存在しつつ、falseの場合はループバックは無効にする。つまり存在しないか、存在していてもtrueの場合はループバックされる
    params:
      <<: *params
      init_images: []
      denoising_strength: 0.75
      alwayson_scripts:
        "ControlNet":
          args:
            - module: "tile_resample"
              model: "control_v11f1e_sd15_tile [a371b31b]"
              processor_res: 64
              threshold_a: 1
              threshold_b: 64
              resize_mode: 1  # Just Resize, Scale to Fit (Inner Fit), Envelope (Outer Fit)
      script_name: "Ultimate SD upscale"
      script_args:
        - 0  # _
        - 512  # tile_width
        - 0  # tile_height
        - 24  # mask_blur
        - 64  # padding
        - 64  # seams_fix_width
        - 0.35  # seams_fix_denoise
        - 64  # seams_fix_padding
        - 3  # upscaler_index
        - True  # save_upscaled_image
        - 1  # redraw_mode "Linear", "Chess", "None"
        - False  # save_seams_fix_image
        - 16  # seams_fix_mask_blur
        - 0  # seams_fix_type "None", "Band pass", "Half tile offset pass", "Half tile offset pass + intersections"
        - 2  # target_size_type "From img2img2 settings", "Custom size", "Scale from image size"
        - 0  # custom_width
        - 0  # custom_height
        - *scale_2 # custom_scale
