f_prompt: "dog riding a skateboard" # 最初に開始するプロンプト。ダイナミックプロンプトが有効なので、一回目はこのプロンプトを使用する。２回目以降からはパースされたプロンプトを使用する
f_negative_prompt: "cat"  # 最初に開始するネガティブプロンプト
default_params: &params
  sampler_name: DPM++ 2M Karras
  steps: 8
  width: 512
  height: 512
  cfg_scale: 7
  seed: -1
  save_images: true
loopbacks:
  - api_endpoint: "/sdapi/v1/txt2img"
    params:
      <<: *params
      alwayson_scripts:
        "Dynamic Prompts v2.11.1":  &dp
          args:
            - True  # is_enabled
            - False  # is_combinatorial
            - 0  # combinatorial_batches
            - False  # is_magic_prompt
            - False  # is_feeling_lucky
            - False  # is_attention_grabber
            - 0  # min_attention
            - 0  # max_attention
            - 0  # magic_prompt_length
            - ""  # magic_temp_value
            - 0  # use_fixed_seed
            - ""  # unlink_seed_from_prompt
            - ""  # disable_negative_prompt
            - null  # enable_jinja_templates
            - null  # no_image_generation
            - 0  # max_generations
            - ""  # magic_model
            - null  # magic_blocklist_regex
  - api_endpoint: "/sdapi/v1/img2img"
    params:
      <<: *params
      denoising_strength: 0.35
      script_name: "Ultimate SD upscale"
      script_args:
            - 0  # _
            - 512  # tile_width
            - 0  # tile_height
            - 24  # mask_blur
            - 64  # padding
            - 64  # seams_fix_width
            - 0.35  # seams_fix_denoise
            - 64  # seams_fix_padding
            - 3  # upscaler_index
            - True  # save_upscaled_image
